// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC19s7DOt7Z9iso1AxdoydlpJ9EhJ0WpNU',
    appId: '1:832498994309:web:42132082dec605b562edec',
    messagingSenderId: '832498994309',
    projectId: 'mappls-hackathon',
    authDomain: 'mappls-hackathon.firebaseapp.com',
    storageBucket: 'mappls-hackathon.appspot.com',
    measurementId: 'G-SEFCTZ2V5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXJ0ZhqFewqUYOpuKg6lfBcPZqTuwwWwI',
    appId: '1:832498994309:android:8bce558f78f3f76262edec',
    messagingSenderId: '832498994309',
    projectId: 'mappls-hackathon',
    storageBucket: 'mappls-hackathon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1AXTuxelcLzLxpKdLg35NSfbkbanpPUg',
    appId: '1:832498994309:ios:ea963fa0109ed93462edec',
    messagingSenderId: '832498994309',
    projectId: 'mappls-hackathon',
    storageBucket: 'mappls-hackathon.appspot.com',
    iosClientId: '832498994309-547p3suu4u5tt9ae3ab4ojcce3c3c9bv.apps.googleusercontent.com',
    iosBundleId: 'com.example.mapplsHackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1AXTuxelcLzLxpKdLg35NSfbkbanpPUg',
    appId: '1:832498994309:ios:b6980610c80b8cd362edec',
    messagingSenderId: '832498994309',
    projectId: 'mappls-hackathon',
    storageBucket: 'mappls-hackathon.appspot.com',
    iosClientId: '832498994309-oufssv36rhhabtn986om02p22t9bsuqh.apps.googleusercontent.com',
    iosBundleId: 'com.example.mapplsHackathon.RunnerTests',
  );
}
